"""add admin_reply to review and question

Revision ID: 65e76a4d3db0
Revises: 4d6ed660f662
Create Date: 2025-06-25 23:41:22.378821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65e76a4d3db0'
down_revision: Union[str, Sequence[str], None] = '4d6ed660f662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('admin_reply', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('admin_reply', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'admin_reply')
    op.drop_column('questions', 'admin_reply')
    # ### end Alembic commands ###
